# Generated by Django 3.0.8 on 2020-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200725_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
