# Generated by Django 3.0.8 on 2020-07-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200727_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='status',
            new_name='winning_Bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='status',
            new_name='active',
        ),
    ]
