# Generated by Django 3.0.8 on 2020-07-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(related_name='watchlist', to='auctions.Listing'),
        ),
    ]
