# Generated by Django 3.0.8 on 2020-07-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200729_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
