# Generated by Django 3.0.8 on 2020-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_top_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='top_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='top_bid',
            field=models.IntegerField(default=0),
        ),
    ]
