# Generated by Django 3.0.8 on 2020-08-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200809_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('', ''), ('bn', 'Brand New'), ('u1', 'Used once'), ('us', 'Used')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cat1',
            field=models.CharField(blank=True, choices=[('', ''), ('el', 'Electronics'), ('sp', 'Sports'), ('ed', 'Education'), ('ty', 'Toys'), ('ar', 'Art'), ('cl', 'Clothes'), ('bf', 'Beauty and Fragrances'), ('hm', 'Home')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cat2',
            field=models.CharField(blank=True, choices=[('', ''), ('el', 'Electronics'), ('sp', 'Sports'), ('ed', 'Education'), ('ty', 'Toys'), ('ar', 'Art'), ('cl', 'Clothes'), ('bf', 'Beauty and Fragrances'), ('hm', 'Home')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cat3',
            field=models.CharField(blank=True, choices=[('', ''), ('el', 'Electronics'), ('sp', 'Sports'), ('ed', 'Education'), ('ty', 'Toys'), ('ar', 'Art'), ('cl', 'Clothes'), ('bf', 'Beauty and Fragrances'), ('hm', 'Home')], max_length=2),
        ),
    ]
