# Generated by Django 3.0.8 on 2020-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200813_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cat1',
            field=models.CharField(blank=True, choices=[('', ''), ('el', 'Electronics'), ('sp', 'Sports'), ('ed', 'Education'), ('ty', 'Toys'), ('bk', 'Books'), ('ar', 'Art'), ('lx', 'Luxury'), ('cl', 'Clothes'), ('jw', 'jw'), ('bf', 'Beauty and Fragrances'), ('hm', 'Home'), ('ac', 'Accessories')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cat2',
            field=models.CharField(blank=True, choices=[('', ''), ('el', 'Electronics'), ('sp', 'Sports'), ('ed', 'Education'), ('ty', 'Toys'), ('bk', 'Books'), ('ar', 'Art'), ('lx', 'Luxury'), ('cl', 'Clothes'), ('jw', 'jw'), ('bf', 'Beauty and Fragrances'), ('hm', 'Home'), ('ac', 'Accessories')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cat3',
            field=models.CharField(blank=True, choices=[('', ''), ('el', 'Electronics'), ('sp', 'Sports'), ('ed', 'Education'), ('ty', 'Toys'), ('bk', 'Books'), ('ar', 'Art'), ('lx', 'Luxury'), ('cl', 'Clothes'), ('jw', 'jw'), ('bf', 'Beauty and Fragrances'), ('hm', 'Home'), ('ac', 'Accessories')], max_length=2),
        ),
    ]
