# Generated by Django 3.0.8 on 2020-08-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20200815_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
